services:
  - type: web
    name: health-analysis-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd app && python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: OPENROUTER_API_KEY
        sync: false
      - key: MODEL_NAME
        value: deepseek/deepseek-chat-v3-0324:free
